spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: 1504
      database: timurdb
      port: 27017
      host: localhost
      auto-index-creation: true